name: Build CI

# Trigger the workflow on push
on: [push]

jobs:
  job1:
    name: Android Builds
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Base Setup
        run: npm run ci.base.setup

      - name: Lint
        run: npm run ci.tslint

      - name: Build Vanilla Android Demo App
        run: npm run ci.vanilla.android.build
